openapi: '3.0.0'
info:
  version: 1.0.0
  title: Forest api
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /forest:
    get:
      summary: List all forests
      operationId: listForests
      tags:
        - forest
      responses:
        '200':
          description: A forest list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forest'
    post:
      summary: Create a new forest
      operationId: createForest
      tags:
        - forest
      requestBody:
        description: Forest to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forest'
      responses:
        '201':
          description: Forest created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forest'

  /forest/{id}:
    get:
      summary: Info for a forest
      operationId: getForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A forest was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forest'
        '404':
          description: Forest not found
    put:
      summary: Update a forest
      operationId: updateForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
            format: uuid
      requestBody:
        description: Forest to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forest'
      responses:
        '200':
          description: Forest updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forest'
        '404':
          description: Forest not found
    delete:
      summary: Delete a forest
      operationId: deleteForest
      tags:
        - forest
      parameters:
        - name: id
          in: path
          required: true
          description: The forest id
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Forest deleted successfully
        '404':
          description: Forest not found

  /tree:
    get:
      summary: List all trees
      operationId: listTrees
      tags:
        - tree
      responses:
        '200':
          description: A tree list was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tree'
    post:
      summary: Create a new tree
      operationId: createTree
      tags:
        - tree
      requestBody:
        description: Tree to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tree'
      responses:
        '201':
          description: Tree created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'

  /tree/{id}:
    get:
      summary: Info for a tree
      operationId: getTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A tree was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
        '404':
          description: Tree not found
    put:
      summary: Update a tree
      operationId: updateTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
            format: uuid
      requestBody:
        description: Tree to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tree'
      responses:
        '200':
          description: Tree updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
        '404':
          description: Tree not found
    delete:
      summary: Delete a tree
      operationId: deleteTree
      tags:
        - tree
      parameters:
        - name: id
          in: path
          required: true
          description: The tree id
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Tree deleted successfully
        '404':
          description: Tree not found

components:
  schemas:
    Species:
      type: string
      enum:
        - OAK
        - EVERGREEN_OAK
        - FIR
        - ASH
        - BEECH
    Exposure:
      type: string
      enum:
        - SUNNY
        - MID_SHADOW
        - SHADOW
    ForestType:
      type: string
      enum:
        - BOREAL
        - TEMPERATE
        - TROPICAL
    Forest:
      required:
        - id
        - type
        - surface
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/ForestType'
        surface:
          type: number
          format: double
          description: Surface area in some unit
        trees:
          type: array
          items:
            $ref: '#/components/schemas/Tree'
    Tree:
      required:
        - birth
        - species
        - exposure
        - carbonStorageCapacity
      properties:
        id:
          type: string
          format: uuid
        birth:
          type: string
          format: date
        species:
          $ref: '#/components/schemas/Species'
        exposure:
          $ref: '#/components/schemas/Exposure'
        carbonStorageCapacity:
          type: number
          format: double
          minimum: 10
          maximum: 50
